spring.application.name=TokenAuth

jwt.scretKey=my_very_long_secretKey_1023456_for_excryption

spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.url=jdbc:mysql://localhost:3306/Security
spring.datasource.username=root
spring.datasource.password=102130

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
